### PR TITLE
Issue #560: fix stack overflow in ignore pattern

### LINKED ISSUE #560: stack overflow in releasenotes-builder
After merging https://github.com/checkstyle/checkstyle/commit/22005947e30d5aa41f1909838e912cf296f6b262 the ci on checkstyle master fails with
```
Exception in thread "main" java.lang.StackOverflowError
        at java.base/java.util.regex.Pattern$CharProperty.match(Pattern.java:3992)
        at java.base/java.util.regex.Pattern$Branch.match(Pattern.java:4800)
        at java.base/java.util.regex.Pattern$GroupHead.match(Pattern.java:4855)
        at java.base/java.util.regex.Pattern$Loop.match(Pattern.java:4964)
        at java.base/java.util.regex.Pattern$GroupTail.match(Pattern.java:4886)
        at java.base/java.util.regex.Pattern$BranchConn.match(Pattern.java:4763)
        at java.base/java.util.regex.Pattern$CharProperty.match(Pattern.java:3996)
        at java.base/java.util.regex.Pattern$Branch.match(Pattern.java:4800)
        at java.base/java.util.regex.Pattern$GroupHead.match(Pattern.java:4855)
```
Note that this commit has very long description.

Removing the commit in the local repo solves the problem. We need to review the pattern and fix it.

### PR DESCRIPTION
**Pull request by pbludov**
Fixes #560

The existing pattern validates the presence of "\n" at the end of the message. But this is not necessary. All messages are checked in CI.
To skip some release notes, it is enough to simply examine the beginning of the message.

All message matching code extracted to a helper class `CommitMessage`.

### CODE REVIEW

**Review by romani — APPROVED** [review]
It would be better to prove that it works by UT.

**Comment by pbludov** [comment]
> It would be better to prove that it works by UT.

The class `NotesBuilder` is a monolithic class with one factory method that opens an internet connection. It is realy hard to test such class. I'll try to extract come testable code from this class.

File: releasenotes-builder/src/main/java/com/github/checkstyle/github/NotesBuilder.java [hunk 1]
```diff
@@ -107,15 +98,13 @@ public static Result buildResult(String localRepoPath, String authToken, String
...
         for (RevCommit commit : commitsForRelease) {
-            String commitMessage = commit.getFullMessage();
-            if (isRevertCommit(commitMessage)) {
-                System.out.println(commitMessage);
-                final int firstQuoteIndex = commitMessage.indexOf('"');
-                final int lastQuoteIndex = commitMessage.lastIndexOf('"');
-                commitMessage = commitMessage.substring(firstQuoteIndex, lastQuoteIndex);
+            CommitMessage commitMessage = new CommitMessage(commit.getFullMessage());
+            if (commitMessage.isRevert()) {
+                System.out.println(commitMessage.getMessage());
```
Comment (pbludov) [inline releasenotes-builder/src/main/java/com/github/checkstyle/github/NotesBuilder.java:103]: Do we need this `System.out.println`?

File: releasenotes-builder/src/test/java/com/github/checkstyle/github/CommitMessageTest.java [hunk 2]
```diff
@@ -0,0 +1,160 @@
...
+    public void testReleaseIsIgnored() {
+        final CommitMessage message = new CommitMessage(
+            "[maven-release-plugin] prepare release checkstyle-8.35");
+        Assert.assertTrue("Message should match ignore pattern", message.isIgnored());
+    }
+
+    @Test
+    public void testUpdateToIsIgnored() {
+        final CommitMessage message = new CommitMessage(
+            "update to 7.0-SNAPSHOT");
```
Comment (pbludov) [inline releasenotes-builder/src/test/java/com/github/checkstyle/github/CommitMessageTest.java:74]: This seems to be outdated and replaced with `"config: update to ...`

File: releasenotes-builder/src/main/java/com/github/checkstyle/github/CommitMessage.java [hunk 3]
```diff
@@ -0,0 +1,134 @@
...
+import java.util.regex.Matcher;
+import java.util.regex.Pattern;
+
+/**
+ * Commit message wrapper.
+ */
+/* package */ class CommitMessage {
+
+    /** Regexp pattern for revert commit messages. */
+    private static final Pattern REVERT_COMMIT_MESSAGES_PATTERN =
```
Comment (pbludov) [inline releasenotes-builder/src/main/java/com/github/checkstyle/github/CommitMessage.java:31]: This pattern can be extended to match reverted commit message and hash.

**Review by romani — APPROVED** [review]

File: releasenotes-builder/src/main/java/com/github/checkstyle/github/NotesBuilder.java (hunk 1 above)
Comment (romani) [reply releasenotes-builder/src/main/java/com/github/checkstyle/github/NotesBuilder.java:103]: I am not sure

**Comment by romani** [comment]
It is huge steps forward.
